### ISSUE TITLE
Användandet av $wpdb->delete innebär att term_relationsships aldrig tas bort

### ISSUE THREAD

**Issue by lakrisgubben** [klandestino/featured-content-manager#1]
Så alla inlägg som någonsin legat i FCM finns kvar i wp_term_relationsships, både för deras area och om en har några eventuella extrafält för taxonomier. Tror vi bör gå bort ifrån alla de har grejerna som kör $wpdb-> direkt på massor av post objekt, är svårt att få överblick över vad man kan missa... :) Om det är att det blir väldigt segt med mass-deleting så kan vi prova o köra typ [wp_defer_term_counting](functions)( true ) innan den loopen och sen wp_defer_term_counting( false ) efter så räknar den iaf bara sådana tunga saker en gång.

**Comment by redundans** [comment]
Nu är detta uppdaterat. Men kan behöva testas innan issue:n stängs.
