### ISSUE TITLE
Questions and nitpicking about class-customizer.php

### ISSUE THREAD

**Issue by lakrisgubben** [klandestino/featured-content-manager#2]
- [x] Unused $wpdb: https://github.com/klandestino/featured-content-manager/blob/a2d937f056b75249ee3ffb59658dbe0bc40a22ee/includes/class-customizer.php#L289
- [x] "Default" comment: https://github.com/klandestino/featured-content-manager/blob/a2d937f056b75249ee3ffb59658dbe0bc40a22ee/includes/class-customizer.php#L57
- [x] I'm struggling to understand what $converts does.. :) https://github.com/klandestino/featured-content-manager/blob/a2d937f056b75249ee3ffb59658dbe0bc40a22ee/includes/class-customizer.php#L320
- [x] This seems unneccesary since the featured image is set a few lines down? Also uses incorrect meta_key 'thumbnail_id' instead of '_thumbnail_id': https://github.com/klandestino/featured-content-manager/blob/a2d937f056b75249ee3ffb59658dbe0bc40a22ee/includes/class-customizer.php#L348

**Comment by redundans** [comment]
Fixed them all. Last issue was a way to solv legacy meta from earlier version of the plugin. Shouldnt be a problem any more.
