### ISSUE TITLE
Questions and nitpicking about class-featured-content.php

### ISSUE THREAD

**Issue by lakrisgubben** [klandestino/featured-content-manager#3]
- [ ] This should be an if ( isset( $args[..] ) ), like in the [method above](https://github.com/klandestino/featured-content-manager/blob/a2d937f056b75249ee3ffb59658dbe0bc40a22ee/includes/class-featured-content.php#L21)?: https://github.com/klandestino/featured-content-manager/blob/a2d937f056b75249ee3ffb59658dbe0bc40a22ee/includes/class-featured-content.php#L73

**Comment by redundans** [comment]
Pushed commit that should solve this.
