### ISSUE TITLE
Questions and nitpicking about class-rest.php

### ISSUE THREAD

**Issue by lakrisgubben** [klandestino/featured-content-manager#5]
- [ ] Is it possible to trigger this condition? If I'm reading https://developer.wordpress.org/reference/functions/get_post_status/ correctly post_status will only be false if sending in a non-existant post. But then that would've been catched in the if-statement above because get_post_type would've returned false: https://github.com/klandestino/featured-content-manager/blob/a2d937f056b75249ee3ffb59658dbe0bc40a22ee/includes/class-rest.php#L135
- [ ] Not really a security issue, but shouldn't there be a permission_callback on the search_posts endpoint as well? Or is that taken care of because it's a private post_type? https://github.com/klandestino/featured-content-manager/blob/36bc0ff2bc07090ca382cd21f93302ca3d4e5dcc/includes/class-rest.php#L24
- [ ] I think this is the same issue as in https://github.com/klandestino/featured-content-manager/issues/2 where featured image is set twice? https://github.com/klandestino/featured-content-manager/blob/36bc0ff2bc07090ca382cd21f93302ca3d4e5dcc/includes/class-rest.php#L225
- [ ] It should use $org_post_id instead of $post->ID to be consistent throughout the method? https://github.com/klandestino/featured-content-manager/blob/36bc0ff2bc07090ca382cd21f93302ca3d4e5dcc/includes/class-rest.php#L231

**Comment by lakrisgubben** [comment]
@redundans the permission callback on the search endpoint broke search, maybe because there's no nonce sent with that request? Not sure...

**Comment by redundans** [comment]
@lakrisgubben Fixed the nonce-problem.
