### ISSUE TITLE
Märk ut tidsinställda artiklar i customizern

### ISSUE THREAD

**Issue by lakrisgubben** [klandestino/featured-content-manager#6]
Lawa gjorde ett förslag på hur artiklar som är tidsinställda skulle kunna se ut i customizern. För att detta ska funka även i listan över arean och inte bara sök så antar jag att vi borde tidsinställa även featured-content posterna ifall originalposten är tidsinställd..? Det borde väl väl göra ändå egentligen för att det är logiskt att en på framsidan inte ska behöva ta hänsyn till tid när en frågar efter dem. Utan en borde få publicerade, och sen i customizern kan en visa poster med draft lr publish som status..

vad säger du @redundans 

![Alt-02](https://user-images.githubusercontent.com/1754954/64616625-3b70eb80-d3dd-11e9-82fb-5e465cb5ded5.png)

**Comment by redundans** [comment]
Det tycker jag låter som en vettig lösning. En tanke om Lawa's form är att kanske byta ut Post Typ som ändå överlappas av tiden för publicering hos de tidsinställda. Antingen till publiceringsdatum eller kanske ta bort helt och hållet. Vad tycker du?

**Comment by lakrisgubben** [comment]
mm.. Känns som det är rätt irrelevant info med post-typ. Tid känns ju mer relevant på alla, om man har typ två artiklar med snarlika titlar. Kanske använda https://developer.wordpress.org/reference/functions/human_time_diff/

**Comment by redundans** [comment]
Skapade en PR som du kan kontrollera för denna issue.
